export const ScreenNames = {
  // AUTH //
  ON_BOARDING: 'onboarding',
  LOGIN: 'login',
  FORGET_PASSWORD: 'forgetpassword',
  VERIFICATION_CODE: 'verificationcode',
  CREATE_NEW_PASS: 'createnewpass',
  REGISTER: 'register',
  PERSONAL_DETAILS: 'Personal Details',
  PERSONAL_DETAILS2: 'Personal Details2',
  DATE_OF_BIRTH: 'dateofbirth',
  WEIGHT: 'weight',
  DIET_PALN: 'Diet Plan',

  // SCREENS//

  BOTTOM_STACK: 'bottomStack',
  USER_HOME: 'Home',
  CHAT: 'Chat',
  PROFILE: 'Profile',
  ABOUT: 'about',
  MESSAGE: 'message',
  NOTIFICATION: 'notification',
  CHANGE_PASSWORD: 'changepass',
  NEW_PASSWORD: 'newpass',
  PRIVACY_POLICY: 'privacypolicy',
  TERMS_AND_CONDITION: 'termscondition',
  FAQS: 'faq',
  TRAINER_HOME: 'Home',
  CLIENTS: 'My Clients',
  MY_CLIENTS_REQ: 'Request Clients',
  EARNINGS: 'Earning',
  CLIENTS_REQUEST: 'Clients Request',
  CLIENTS_REGISTER: 'Clients Register',
  CLIENTS_REGISTER1: 'Clients Register1',
  CLIENTS_REGISTER2: 'Clients Register2',
  CLIENTS_REGISTER3: 'Clients Register3',
  PLAN_SUCCESS: 'PlanSuccess',
  CLIENTS_PROFILE: 'Client Profile',
  RATING: 'Rating',
  EDIT_PROFILE: 'edit profile',
};
